add_newline = false

format = """
[](#ff00ff)\
$username\
[](bg:#00ffff fg:#ff00ff)\
$directory\
[](fg:#00ffff bg:#00ff99)\
$git_branch\
[](fg:#00ff99)\
$character
"""

[username]
style_user = "bg:#ff00ff fg:#000000 bold"
show_always = true

[directory]
style = "bg:#00ffff fg:#000000 bold"

[git_branch]
style = "bg:#00ff99 fg:#000000 bold"

[character]
success_symbol = "[➜](bold #ff00ff)"
error_symbol = "[➜](bold #ff0000)"